ARG BASE_IMAGE="ubuntu:24.04"

FROM $BASE_IMAGE

ARG BASE_IMAGE
ENV BASE_IMAGE=$BASE_IMAGE

ARG ABC=0
ENV ABC=$ABC

ARG XYZ=0
ENV XYZ=$XYZ

RUN printenv | tee /env.txt

COPY test.txt /test.txt
COPY .hidden.txt /.hidden.txt
COPY subdir /subdir
COPY .subdir /.subdir
