# .github/workflows/test_script.yml

# Copyright (c) 2024 Tim Perkins

name: Test HN2B Script

on:
  push:
    branches:
      - main
    tags:
      - "**"
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Test HN2B Script
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10
      - name: Install Cosign
        uses: sigstore/cosign-installer@6f9f17788090df1f26f669e9d70d6ae9567deba6
      - name: Install Regctl
        uses: regclient/actions/regctl-installer@087497936f11371287370b6d4e1e694e66ebd744
        with:
          release: v0.11.5
      - name: Install Prysk
        run: |
          # The flag may or may not be necessary because there is no Venv
          pip install --break-system-packages prysk
      - name: Run Lint
        run: |
          make lint
      - name: Run Tests
        run: |
          make test
